// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfjiyrvgnhxrfvobtpqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmaml5cnZnbmh4cmZ2b2J0cHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDc3NjQsImV4cCI6MjA1ODcyMzc2NH0.YP210tWf6WXq3rnR430Q56jybjkIbJOvQ99nCOvvTdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);