// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mflnkovhstgbgjmofqkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mbG5rb3Zoc3RnYmdqbW9mcWt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTMzMDksImV4cCI6MjA1ODY2OTMwOX0.k5hui-XPJcMprcQ3dutPfuPxfrwHgnXOLzDn1E--i8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);